allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  canvas: true
  es5-ext: true
  unrs-resolver: true

overrides:
  decode-uri-component: ^0.5.0
  webpack: ^5.104.1
  form-data: ^4.0.6
  terser: ^5.14.2
  marked: ^4.0.10
  node-fetch: ^2.6.7
  lodash: ^4.18.0
  semver@5: ^5.7.2
  semver@6: ^6.3.1
  minimatch@3: ^3.1.3
  tough-cookie: ^4.1.3
  tar: ^7.5.18
  braces: ^3.0.3
  simple-get: ^3.1.1
  cross-spawn: ^7.0.5
  js-yaml: ^4.3.2
